version: "3.1"

services:

  db:
    container_name: mysql_db
    image: mysql:8.0.21
    restart: always
    env_file: env
    networks: 
      - myrecipes
  
  flask_app:
    container_name: mysql_flask
    build: ./app
    depends_on: 
      - db   
    ports:
      - 4001:3001
    volumes:
      - .:/app
    networks:
      - myrecipes
    command: sh -c "python main.py"

networks: 
  myrecipes: {}
